services:
  - type: web
    name: django-backend
    env: python
    rootDir: .
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn dechets_ko.wsgi:application
    postDeployCommand: |
      python manage.py makemigrations
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python manage.py populate_data
    #envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        value: "ta_cle_secrete"
      - key: DEBUG
        value: "False"

databases:
  - name: django-db
    plan: free
